name: Fetch Monthly Data

on:
  schedule:
    - cron: '00 16 30 * *' # Runs at 4 PM UTC (12 AM MYT on the 1st day of the month)

jobs:
  run-python:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x' # Replace with the version you need

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run Python script
        run: |
          python fetch_monthly.py

      - name: Commit changes
        run: |
          git config --local user.name "GitHub Action"
          git config --local user.email "action@github.com"
          git fetch origin main
          git rebase origin/main || git rebase --abort
          git add -A
          git commit -m "Update at $(date +'%m-%Y')" || echo "No changes to commit"

      - name: Push changes
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: main
